language: java
sudo: false
install: true
jdk:
 - oraclejdk8

before_install:
  - chmod +x mvnw
after_success: 
  - bash <(curl -s https://codecov.io/bash) -t $CODE_COV 
  
cache:
  directories: 
    - .autoconf
    - '$HOME/.m2'
    - '$HOME/.sonar/cache'
addons:
  sonarcloud:
    organization: nsimonin1-github
    token: cb5a880812481610d106e067f344030e22c3d9ef
script:
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
