language: java
sudo: false
install: true
jdk:
 - oraclejdk8

before_install:
  - chmod +x mvnw
after_success: 
  - bash <(curl -s https://codecov.io/bash) -t $CODE_COV 
  
cache:
  directories: 
    - .autoconf
    - '$HOME/.m2'
    - '$HOME/.sonar/cache'
addons:
  sonarcloud:
    organization: nsimonin1-github
    token: $SONAR_QUBE
script:
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
deploy:
  provider: cloudfoundry
  username: nsimonin1@gmail.com
  password: $PIVOTAL_CLOUD
  api: https://api.run.pivotal.io
  organization: ngos-project
  space: staging
  #manifest: manifest-staging.yml       # (optional)  Defaults to manifest.yml.
  app_name: transport                # (optional)
  
  
  
  
