language: java
jdk:
 - oraclejdk8

before_install:
  - chmod +x mvnw
after_success: 
  - bash <(curl -s https://codecov.io/bash) -t $CODE_COV 
  
cache:
  directories: 
    - .autoconf
    - $HOME/.m2
